### ISSUE TITLE
First draft of API

### ISSUE THREAD

**Issue by LeoLTM** [victoriakallerud/FlagQuest#2]
## Description

**Sub-Tasks:**
- [x] Create an overview to define the requirements for the communication interfaces
- [x] Decide on a backend framework (-> NodeJS with NestJS)
- [x] Write basic SwaggerIO API documentation
- [x] #6
- [x] #7

## Issues
The issues that occurred while solving the task
